/**
 * Build the runtime client-plugin artifact.
 *
 * The harness evaluates a dynamic Client plugin's `code.client` as a plain
 * function body (its closure provides injected builtins such as `styles`).
 * This script bundles the TypeScript entry into one self-contained ESM module,
 * then strips the ESM `export` syntax so the result is exactly that function
 * body — written to `dist/client.js`.
 *
 * Load the artifact by passing `dist/client.js` contents as `code.client` to
 * `cordis_define` (new plugin) and activating with `cordis_run`.
 */
import { build } from "esbuild";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = resolve(rootDir, "src/client.ts");
const outDir = resolve(rootDir, "dist");
const outFile = resolve(outDir, "client.js");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "browser",
  sourcemap: false,
  minify: false,
  legalComments: "none",
  write: false,
  logLevel: "silent",
});

let code = result.outputFiles[0].text;

// esbuild hoists a default export to `var <name> = <plugin>` and emits a
// trailing `export { <name> as default }` block. Rewrite that block (or an
// inline `export default <expr>`) into `return <name>;` so the bundle is a
// plain function body that returns the plugin.
const exportBlock = code.match(/export\s*\{\s*([A-Za-z_$][\w$]*)\s+as\s+default\s*\}\s*;?/s);
if (exportBlock) {
  code = code.replace(exportBlock[0], `return ${exportBlock[1]};`);
} else {
  code = code.replace(/^[ \t]*export\s+default\s+/gmu, "return ");
}

// Fail loudly if any module syntax survived — a function body must not import
// or export. (esbuild bundles all imports, so this should never trigger.)
if (/\b(?:import|export|require)\b/.test(code)) {
  throw new Error("Build output still contains module syntax; cannot emit function body.");
}

// The function body must end by returning the plugin object.
if (!/return\s+[A-Za-z_$][\w$]*\s*;?\s*$/s.test(code)) {
  throw new Error("Build output does not end with a return of the plugin.");
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const header =
  "/**\n" +
  " * DeepSeek Harness — Japanese locale injector (Client plugin body).\n" +
  " * GENERATED by `pnpm build` (scripts/build.mjs). Do not edit by hand.\n" +
  " * Source: src/client.ts. Pass this file's contents as `code.client`.\n" +
  " */\n";

await writeFile(outFile, header + code, "utf8");

console.log("✔ built dist/client.js (self-contained client plugin body)");
